export enum colors {
  surface = "#E9F1F4",
  surfacesubtle = "#FFFFFF",
  surfacealt = "#F8F9FA",
  textdefault = "#1F2D3A",
  textsubtle = "#4A5568",
  accentprimary = "#2E8C96",
  accentsecondary = "#2A7A84",
  success = "#30a46c",
  warning = "#ffd13f",
  danger = "#e54d2e",
  tintpurple = "#e2dffe",
  tintsuccess = "#adddc0",
  tintwarning = "#ffffc4",
  tintdanger = "#ffdadc",
}
